/**
 * Feature ↔ test gate (docs/PLAN.md §10, docs/CONTRACTS.md §5).
 *
 * Reads features.yaml, checks that every `done` feature lists at least one existing, non-skipped test
 * (`file#title`, the title inside an it(/test( call), that every `[F-0xx]` tag in a test file maps to a
 * known feature, and renders docs/ACCEPTANCE.md. Exit 1 on any violation.
 *
 *   npx tsx scripts/check-features.ts [--root <dir>] [--check]   (--check: fail if ACCEPTANCE.md is stale)
 */
import { existsSync, readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { join, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { parse } from 'yaml';

export type FeatureStatus = 'planned' | 'in-progress' | 'done';

export interface Feature {
  id: string;
  title: string;
  practice?: string;
  status: FeatureStatus;
  tests: string[];
  manual?: string[];
}

export interface TestCall {
  title: string;
  modifiers: string[]; // e.g. ['skip'], ['todo'], ['each']
  line: number;
}

export interface CheckResult {
  ok: boolean;
  errors: string[];
  features: Feature[];
  acceptance: string; // rendered markdown
}

export const TEST_DIRS = ['src', 'test', 'e2e', 'scripts'];
export const TEST_FILE = /\.(test|spec)\.(ts|tsx|js|mjs)$/;
export const TAG = /\[F-\d{3}\]/g;
const STATUSES: FeatureStatus[] = ['planned', 'in-progress', 'done'];

/** Every `it(`/`test(` (with optional .skip/.todo/.only/… chain) whose first argument is a string literal. */
const CALL =
  /\b(it|test)((?:\.(?:skip|todo|only|each|concurrent|fails|sequential|runIf|skipIf|todoIf|for))*)\s*\(\s*(['"`])((?:\\.|(?!\3)[^\\])*)\3/g;

export function extractTestCalls(source: string): TestCall[] {
  const calls: TestCall[] = [];
  for (const m of source.matchAll(CALL)) {
    const modifiers = m[2] ? m[2].split('.').filter(Boolean) : [];
    const raw = m[4];
    const title = raw.replace(/\\(['"`\\])/g, '$1');
    const line = source.slice(0, m.index).split('\n').length;
    calls.push({ title, modifiers, line });
  }
  return calls;
}

export function listTestFiles(root: string): string[] {
  const out: string[] = [];
  const walk = (dir: string) => {
    if (!existsSync(dir)) return;
    for (const name of readdirSync(dir)) {
      if (name === 'node_modules' || name.startsWith('.')) continue;
      const p = join(dir, name);
      if (statSync(p).isDirectory()) walk(p);
      else if (TEST_FILE.test(name)) out.push(p);
    }
  };
  for (const d of TEST_DIRS) walk(join(root, d));
  return out.sort();
}

export function loadFeatures(root: string): Feature[] {
  const file = join(root, 'features.yaml');
  if (!existsSync(file)) throw new Error(`features.yaml not found in ${root}`);
  const raw = parse(readFileSync(file, 'utf8'));
  if (!Array.isArray(raw)) throw new Error('features.yaml must be a list');
  return raw.map((f, i) => {
    if (!f || typeof f !== 'object') throw new Error(`features.yaml[${i}] is not a mapping`);
    const id = String(f.id ?? '');
    if (!/^F-\d{3}$/.test(id)) throw new Error(`features.yaml[${i}]: bad id '${id}'`);
    if (!STATUSES.includes(f.status)) {
      throw new Error(`${id}: status must be one of ${STATUSES.join('|')}, got '${f.status}'`);
    }
    return {
      id,
      title: String(f.title ?? ''),
      practice: f.practice ? String(f.practice) : undefined,
      status: f.status,
      tests: Array.isArray(f.tests) ? f.tests.map(String) : [],
      manual: Array.isArray(f.manual) ? f.manual.map(String) : undefined,
    };
  });
}

function mdCell(s: string): string {
  return s.replace(/\|/g, '\\|').replace(/\n/g, ' ');
}

export function renderAcceptance(features: Feature[]): string {
  const lines = [
    '# Acceptance checklist',
    '',
    'Generated by `npm run features` (`scripts/check-features.ts`) from `features.yaml`. Do not edit by hand.',
    'A feature is `done` only when every listed test exists, is not skipped, and CI is green.',
    '',
    '| id | title | status | practice | tests | manual |',
    '|---|---|---|---|---|---|',
  ];
  for (const f of features) {
    const tests = f.tests.length ? f.tests.map((t) => `\`${mdCell(t)}\``).join('<br>') : '—';
    const manual = f.manual?.length ? f.manual.map((m) => mdCell(m)).join('<br>') : '—';
    const status = f.status === 'done' ? '✅ done' : f.status === 'in-progress' ? '🛠 in-progress' : '⬜ planned';
    lines.push(
      `| ${f.id} | ${mdCell(f.title)} | ${status} | ${mdCell(f.practice ?? '')} | ${tests} | ${manual} |`,
    );
  }
  const done = features.filter((f) => f.status === 'done').length;
  lines.push('', `${done} of ${features.length} features done.`, '');
  return lines.join('\n');
}

export function checkFeatures(root: string): CheckResult {
  const errors: string[] = [];
  const features = loadFeatures(root);
  const known = new Set(features.map((f) => f.id));
  const seen = new Set<string>();
  for (const f of features) {
    if (seen.has(f.id)) errors.push(`${f.id}: duplicate id`);
    seen.add(f.id);
  }

  const callCache = new Map<string, TestCall[]>();
  const callsIn = (file: string) => {
    let calls = callCache.get(file);
    if (!calls) {
      calls = extractTestCalls(readFileSync(file, 'utf8'));
      callCache.set(file, calls);
    }
    return calls;
  };

  for (const f of features) {
    if (f.status === 'done' && f.tests.length === 0) {
      errors.push(`${f.id}: status done but no tests listed`);
    }
    for (const ref of f.tests) {
      const hash = ref.indexOf('#');
      if (hash <= 0 || hash === ref.length - 1) {
        errors.push(`${f.id}: test ref '${ref}' must be 'file#title'`);
        continue;
      }
      const file = ref.slice(0, hash);
      const title = ref.slice(hash + 1).trim();
      const abs = join(root, file);
      if (!existsSync(abs)) {
        errors.push(`${f.id}: test file missing: ${file}`);
        continue;
      }
      const matches = callsIn(abs).filter((c) => c.title.trim() === title);
      if (matches.length === 0) {
        errors.push(`${f.id}: title not found in an it()/test() call in ${file}: '${title}'`);
        continue;
      }
      if (f.status === 'done') {
        const live = matches.filter((c) => !c.modifiers.includes('skip') && !c.modifiers.includes('todo'));
        if (live.length === 0) {
          errors.push(`${f.id}: test is skipped/todo in ${file}: '${title}'`);
        }
      }
    }
  }

  for (const file of listTestFiles(root)) {
    const src = readFileSync(file, 'utf8');
    const rel = relative(root, file);
    const tags = new Set([...src.matchAll(TAG)].map((m) => m[0].slice(1, -1)));
    for (const tag of tags) {
      if (!known.has(tag)) errors.push(`${rel}: unknown feature tag [${tag}]`);
    }
  }

  return { ok: errors.length === 0, errors, features, acceptance: renderAcceptance(features) };
}

function main() {
  const argv = process.argv.slice(2);
  const rootIdx = argv.indexOf('--root');
  const root = resolve(rootIdx >= 0 ? argv[rootIdx + 1] : process.cwd());
  const checkOnly = argv.includes('--check');
  const result = checkFeatures(root);
  const out = join(root, 'docs', 'ACCEPTANCE.md');
  if (checkOnly) {
    const current = existsSync(out) ? readFileSync(out, 'utf8') : '';
    if (current !== result.acceptance) {
      result.errors.push('docs/ACCEPTANCE.md is stale — run `npm run features`');
      result.ok = false;
    }
  } else if (existsSync(join(root, 'docs'))) {
    writeFileSync(out, result.acceptance);
  }
  for (const e of result.errors) console.error(`features: ${e}`);
  const done = result.features.filter((f) => f.status === 'done').length;
  console.log(
    `features: ${result.features.length} listed, ${done} done, ${result.errors.length} problem(s)${checkOnly ? '' : ` — wrote ${relative(root, out)}`}`,
  );
  process.exit(result.ok ? 0 : 1);
}

const isMain =
  typeof process.argv[1] === 'string' &&
  resolve(process.argv[1]) === fileURLToPath(import.meta.url);
if (isMain) main();
